import Layout from '@/Components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import profilePic from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from '@/Components/AnimatedText'
import { LinkArrow } from '@/Components/icon'
import HireMe from '@/Components/HireMe'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/Components/TransitionEffect'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <TransitionEffect />
      <main className = 'flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt="SaiPrabhat" className='w-full h-auto lg:hidden md:inline-block md:w-full'
                priority
                sizes="(max-width:768px) 100vw,
                (max-width:1200px) 50vw,
                50vw"
              />
            </div>
            <div className='w-1/2 flex flex-col item-center self-center lg:w-full lg:text-center'>

              <AnimatedText text="Turning Vision Into Reality With Code and Design." className='text-6xl text-left
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl
              '/>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
                A seasoned Full Stack web developer with a passion for crafting exceptional web and mobile applications. With expertise in front-end technologies like React.js and Angular, coupled with strong back-end skills in Node.js and PHP, I create seamless user experiences and scalable solutions. I am dedicated, detail-oriented, and committed to delivering innovative solutions that exceed expectations.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/Sai_Prabhat.pdf" target={"_blank"}
                  className='flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibolds hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-black hover:dark:bg-dark hover:dark:text-light hover:dark:border:light 
                 md:p-2 md:px-4 md:text-base
                '
                  download={false}
                >Resume
                <LinkArrow className={"w-6 ml-1"}/>
                </Link>
                <Link href="mailto:prabhat@uwindsor.ca" target={"_blank"}
                className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base'
                >Contact</Link>
              </div>
          </div>
         </div>
          
        </Layout>
        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
          <Image src={lightBulb} alt="SaiPrabhat" className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}
